name: Checkout Manual
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Default values checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: current folder
        run: |
          python basefinal.py
